# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-27:
  stage: build
  environment:
    ANDROID_COMPILE_SDK: 27
    ANDROID_BUILD_TOOLS: 28.0.3
    ANDROID_SDK_TOOLS: 24.4.1
  script:
    - docker build . -t $CI_REGISTRY_IMAGE:$ANDROID_COMPILE_SDK
    - docker push $CI_REGISTRY_IMAGE:$ANDROID_COMPILE_SDK
  only:
    - master

build-28:
  stage: build
  environment:
    ANDROID_COMPILE_SDK: 28
    ANDROID_BUILD_TOOLS: 28.0.3
    ANDROID_SDK_TOOLS: 24.4.1
  script:
    - docker build . -t $CI_REGISTRY_IMAGE:$ANDROID_COMPILE_SDK
    - docker push $CI_REGISTRY_IMAGE:$ANDROID_COMPILE_SDK
  only:
    - master

build-29:
  stage: build
  environment:
    ANDROID_COMPILE_SDK: 29
    ANDROID_BUILD_TOOLS: 28.0.3
    ANDROID_SDK_TOOLS: 24.4.1
  script:
    - docker build . -t $CI_REGISTRY_IMAGE:$ANDROID_COMPILE_SDK
    - docker push $CI_REGISTRY_IMAGE:$ANDROID_COMPILE_SDK
  only:
    - master